### ISSUE TITLE
prefix installs ruby to non system path

### ISSUE THREAD

**Issue by billxinli** [poise/poise-ruby-build#4]
`prefix` installs ruby to non system path should we use chef's mv command to move to the system path for the binary to be executable?

**Comment by coderanger** [comment]
No, this is designed to allow multiple versions of Ruby to be installed in parallel. Within Chef, `poise-ruby` will take care of using the right executables. If you want to use them outside of Chef, you should write something to your shell init files to update `$PATH`.

**Comment by billxinli** [comment]
Ah okay, thanks, just want to make sure I didn't read things wrong. 
Also I assume by extension `application_ruby` will then use the proper `ruby` as well?
(Apologies for using GH issues for this.)

**Comment by coderanger** [comment]
Yep, internally everything uses the `ruby_binary` and `gem_binary` accessors to get the right absolute paths.
